name: Docker Hub
on: 
   push: 
      branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: publish to docker hub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: pavled/atvss-obavestenja
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
